#!/bin/bash

# Verify we are running as root
if [ "$EUID" -ne 0 ]; then
        echo "Please run as root"
        exit
fi

echo "This script will install 2 cronjobs for Defender"
echo " - Update defender (Saturday)"
echo " - Defender quick scan (Sunday)"
echo ""

# Dump the current crontab to a temporary file
tmpfile=$(mktemp /tmp/crontab.XXXXXX)
crontab -l 2>/dev/null > $tmpfile

# Check if crontab is already present
if cat ${tmpfile} | grep -q mdatp; then
        echo "It seems that there is already a cronjob present for mdatp. Aborting"
        exit
fi

# Select correct update command
which yum >/dev/null && update_command='yum update mdatp -y > /root/mdatp_update_cron_job.log'
which apt-get >/dev/null && update_command='apt-get install --only-upgrade mdatp > /root/mdatp_update_cron_job.log'
which zypper >/dev/null && update_command='zypper update mdatp > /root/mdatp_update_cron_job.log'
if [ -z "$update_command" ]; then
        echo "Script could not determine the package manager that should be used. Aborting"
        exit
fi

# Prompt the user for the hour
while true; do
    read -p "At what hour would you like to run the update/scan [0-23]? " chosen_hour
    if  [ "$chosen_hour" -ge 0 ] && [ "$chosen_hour" -le 23 ]; then
                break;
        else
                echo "Please give an hour in 24hour format [0 - 23].";
    fi
done

# Add our entries to crontab
scan_command='/bin/mdatp scan quick > /root/mdatp_cron_job.log'
echo "0 ${chosen_hour} * * sat ${update_command}" >> $tmpfile
echo "0 ${chosen_hour} * * sun ${scan_command}" >> $tmpfile

# Load the new crontab
crontab $tmpfile

echo "Current crontab:"
crontab -l
echo ""
echo "Done."

# Cleanup
rm $tmpfile
